# Generated by Django 4.2.2 on 2023-06-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('part_no', models.CharField(max_length=7)),
                ('qty', models.CharField(max_length=2)),
                ('replacement', models.CharField(blank=True, max_length=7, verbose_name='Replacement part no.')),
                ('designation', models.CharField(max_length=256)),
                ('additional_information', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=32)),
                ('included', models.BooleanField(default=False, verbose_name='Is in package?')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
