# Generated by Django 4.2.2 on 2023-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pos',
            field=models.CharField(max_length=4),
        ),
    ]
